USE [master]
GO
/****** Object:  Database [TeknorixJobsDb]    Script Date: 21-10-2024 00:59:07 ******/
CREATE DATABASE [TeknorixJobsDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TeknorixJobsDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TeknorixJobsDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TeknorixJobsDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TeknorixJobsDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TeknorixJobsDb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TeknorixJobsDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TeknorixJobsDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TeknorixJobsDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TeknorixJobsDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TeknorixJobsDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TeknorixJobsDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [TeknorixJobsDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET RECOVERY FULL 
GO
ALTER DATABASE [TeknorixJobsDb] SET  MULTI_USER 
GO
ALTER DATABASE [TeknorixJobsDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TeknorixJobsDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TeknorixJobsDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TeknorixJobsDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TeknorixJobsDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TeknorixJobsDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TeknorixJobsDb', N'ON'
GO
ALTER DATABASE [TeknorixJobsDb] SET QUERY_STORE = ON
GO
ALTER DATABASE [TeknorixJobsDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TeknorixJobsDb]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 21-10-2024 00:59:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Departments]    Script Date: 21-10-2024 00:59:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Departments](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Departments] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Jobs]    Script Date: 21-10-2024 00:59:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Jobs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LocationId] [int] NOT NULL,
	[DepartmentId] [int] NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[ClosingDate] [datetime2](7) NOT NULL,
	[PostedDate] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Jobs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Locations]    Script Date: 21-10-2024 00:59:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Locations](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[City] [nvarchar](max) NOT NULL,
	[State] [nvarchar](max) NOT NULL,
	[Country] [nvarchar](max) NOT NULL,
	[Zip] [int] NOT NULL,
 CONSTRAINT [PK_Locations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Jobs_DepartmentId]    Script Date: 21-10-2024 00:59:07 ******/
CREATE NONCLUSTERED INDEX [IX_Jobs_DepartmentId] ON [dbo].[Jobs]
(
	[DepartmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Jobs]  WITH CHECK ADD  CONSTRAINT [FK_Jobs_Departments_DepartmentId] FOREIGN KEY([DepartmentId])
REFERENCES [dbo].[Departments] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Jobs] CHECK CONSTRAINT [FK_Jobs_Departments_DepartmentId]
GO
USE [master]
GO
ALTER DATABASE [TeknorixJobsDb] SET  READ_WRITE 
GO
